# -*- coding: utf-8 -*-
"""Assignment07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11T75jBOhstph-EXHBRttkQXeHs0sWnT_

## 1. What is the name of the feature responsible for generating Regex objects?
"""

The re. compile() function returns Regex objects.

"""## 2. Why do raw strings often appear in Regex objects?"""

Raw strings are used so that backslashes do not have to be escaped.

"""## 3. What is the return value of the search() method?"""

The search() method returns the index (position) of the first match. The search() method 
returns -1 if no match is found. The search() method is case sensitive.

"""## 4. From a Match item, how do you get the actual strings that match the pattern?"""

The group() method returns strings of the matched text.

"""## 5. In the regex which created from the r'(\d\d\d)-(\d\d\d-\d\d\d\d)', what   ## does group zero cover? Group 2? Group 1?"""

Group 0 is the entire match, group 2 covers the second set of parentheses, and group 1 covers the first set of parentheses.

"""## 6. In standard expression syntax, parentheses and intervals have distinct meanings. How can you tell a regex that you want it to fit real parentheses and periods?"""

Periods and parentheses can be escaped with a backslash: \., \(, and \)

"""## 7. The findall() method returns a string list or a list of string tuples. What causes it to return one of the two options?"""

If the regex has no groups, a list of strings is returned. If the regex has groups, a list of tuples of strings is returned

"""## 8. In standard expressions, what does the | character mean?"""

The | character signifies matching "either, or" between two groups.

"""## 9. In regular expressions, what does the character stand for?"""

All characters, except those having special meaning in regex, matches themselves.

"""## 10.In regular expressions, what is the difference between the + and * characters?"""

The + matches one or more. The * matches zero or more

"""## 11. What is the difference between {4} and {4,5} in regular expression?"""

The {4} matches exactly four instances of the preceding group. The {4,5} matches between four and five instances.

"""## 12. What do you mean by the \d, \w, and \s shorthand character classes signify in regular expressions?"""

The \d, \w, and \s shorthand character classes match a single digit, word, or space character, respectively.

"""## 13. What do means by \D, \W, and \S shorthand character classes signify in regular expressions?"""

The \D, \W, and \S shorthand character classes match a single character that is not a digit, word, or space character, respectively.

"""## 14. What is the difference between .*? and .*?"""

The .? performs a greedy match, and the .? performs a nongreedy match.

"""## 15. What is the syntax for matching both numbers and lowercase letters with a character class?"""

Either [0-9a-z] or [a-z0-9]

"""## 16. What is the procedure for making a normal expression in regax case insensitive?"""

use the regular expression /i

"""## 17. What does the . character normally match? What does it match if re.DOTALL is passed as 2nd argument in re.compile()?"""

The . character normally matches any character except the newline character. 
If re.DOTALL is passed as  argument to re.compile(), then the dot will also match newline characters.

"""## 18. If numReg = re.compile(r'\d+'), what will numRegex.sub('X', '11 drummers, 10 pipers, five rings, 4 hen') return?"""

X drummers, X pipers, five rings, X hens

"""## 19. What does passing re.VERBOSE as the 2nd argument to re.compile() allow to do?"""

The re.VERBOSE argument allows you to add whitespace and comments to the string passed to re.compile().

"""## 20. How would you write a regex that match a number with comma for every three digits? It must match the given following:
'42'
'1,234'
'6,368,745'
"""

re.compile(r'^\d{1,3}(,\d{3})*$') will create this regex,
but other regex strings can produce a similar regular expression.