# -*- coding: utf-8 -*-
"""Assignment_03

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mj7uVBy5K_ksrITut8z3JKFMl4pIBaWe

## 1. Why are functions advantageous to have in your programs?
"""



"""The use of functions makes a program more readable. It's frequently difficult to read a large program.
Breaking the code down into smaller functions keeps the program structured, under standable, and reusable.
The function can be reused countless times after it is defined.

## 2. When does the code in a function run: when it's specified or when it's called?
"""

The code in a function executes when the function is called, not when the function is defined.

"""## 3. What statement creates a function?"""



"""var sayHello = function() { }; 
We could put any code inside that function - one statement, multiple statements - depends on what we want to do.

## 4. What is the difference between a function and a function call?
"""



"""A function is a block of code that does a particular operation and returns a result.
It usually accepts inputs as parameters and returns a result.
The parameters are not mandatory.
A function call is the code used to pass control to a function

## 5. How many global scopes are there in a Python program? How many local scopes?
"""



"""GLOBEL SCOPE:-There's only one global Python scope per program execution. This scope remains in existence until the program terminates and all its names are forgotten. Otherwise, the next time you were to run the program, the names would remember their values from the previous run.

LOCAL SCOPE:- Local scope is a characteristic of variables that makes them local (i.e., the variable name is only bound to its value within a scope which is not the global scope)

## 6. What happens to variables in a local scope when the function call returns?
"""



"""the local variables get destroyed.

## 7. What is the concept of a return value? Is it possible to have a return value in an expression?
"""



"""A return statement is used to end the execution of the function call and
“returns” the result (value of the expression following the return

A Python function will always have a return value

## 8. If a function does not have a return statement, what is the return value of a call to that function?
"""



"""If no return statement appears in a function definition, control automatically returns
to the calling function after the last statement of the called function is executed.
In this case, the return value of the called function is undefined.

## 9. How do you make a function variable refer to the global variable?
"""



"""Normally, when you create a variable inside a function, that variable is local,
and can only be used inside that function.To create a global variable inside a
function, you can use the global keyword.

## 10. What is the data type of None?
"""



"""Definition and Usage. The None keyword is used to define a null value, or no value at all.
 None is not the same as 0, False, or an empty string.
None is a data type of its own (NoneType) and only None can be None.

## 11. What does the sentence import areallyourpetsnamederic do?
"""

That import statement imports a module named areallyourpetsnamederic. (This isn't a real Python module, by the way.)

"""## 12. If you had a bacon() feature in a spam module, what would you call it after importing spam?

"""

This function can be called with spam. bacon().

"""## 13. What can you do to save a programme from crashing if it encounters an error?

"""



"""In Python, we use the try and except statements to handle exceptions.
Whenever the code breaks down, an exception is thrown without crashing the

## 14. What is the purpose of the try clause? What is the purpose of the except clause?
"""



"""The try block lets you test a block of code for errors. The except block lets you
handle the error. The else block lets you execute code when there is no error.
The finally block lets you execute code, regardless of the result of the try- and except blocks.
"""





