# -*- coding: utf-8 -*-
"""Assignment_09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13B7SJQ46mwFr7UuwSSLjxVS4HhTdItAQ

## 1. To what does a relative path refer?
"""

A relative path refers to a location that is relative to a current directory.

"""## 2. What does an absolute path start with your operating system?"""

Absolute paths start with the root folder, such as / or C:\.

"""## 3. What do the functions os.getcwd() and os.chdir() do?"""

The os.getcwd() function returns the current working directory. The os.chdir() function changes the current working directory

"""## 4. What are the . and .. folders?"""

The . folder is the current folder, and .. is the parent folder

"""## 5. In C:\bacon\eggs\spam.txt, which part is the dir name, and which part is the base name?"""

C:\bacon\eggs is the dir name, while spam.txt is the base name.

"""## 6. What are the three “mode” arguments that can be passed to the open() function?"""

The string 'r' for read mode, 'w' for write mode, and 'a' for append mode

"""## 7. What happens if an existing file is opened in write mode?"""

An existing file opened in write mode is erased and completely overwritten

"""## 8. How do you tell the difference between read() and readlines()?"""

The read() method returns the file’s entire contents as a single string value. The readlines() method returns a 
list of strings, where each string is a line from the file’s contents.

"""## 9. What data structure does a shelf value resemble?"""

A shelf value resembles a dictionary value; it has keys and values, along with keys() 
 and values() methods that work similarly to the dictionary methods of the same names.